In [1]:
# 多分類 預測一個水果 是 香蕉 蘋果 芭樂 柳丁(只能 四種選一種) Multiclass --> 鳶尾花 分類就是 這個案例
# 多標籤 預測一篇文章 是 散文 時事 科技 文學(允許 多種選多種) MultiLabel
 
# https://scikit-learn.org/stable/modules/multiclass.html

In [2]:
# 匯入資料
import pandas as pd
data = pd.read_csv('diabetes.csv')
data[:3]

PatientID  Pregnancies  PlasmaGlucose  DiastolicBloodPressure  \
0    1354778            0            171                      80   
1    1147438            8             92                      93   
2    1640031            7            115                      47   

   TricepsThickness  SerumInsulin        BMI  DiabetesPedigree  Age  Diabetic  
0                34            23  43.509726          1.213191   21         0  
1                47            36  21.240576          0.158365   23         0  
2                52            35  41.511523          0.079019   23         0

In [3]:
# data.iloc[:, 1:-1]
# data.iloc[:, [-1]]

In [4]:
#X 前面四個欄位的數值
#y 最後一個欄位的數值
X, y = data.iloc[:, 1:-1].values, data.iloc[:, -1].values

In [5]:
# 特徵 尚未進行標準化
X[:3]

array([[0.00000000e+00, 1.71000000e+02, 8.00000000e+01, 3.40000000e+01,
        2.30000000e+01, 4.35097259e+01, 1.21319135e+00, 2.10000000e+01],
       [8.00000000e+00, 9.20000000e+01, 9.30000000e+01, 4.70000000e+01,
        3.60000000e+01, 2.12405757e+01, 1.58364981e-01, 2.30000000e+01],
       [7.00000000e+00, 1.15000000e+02, 4.70000000e+01, 5.20000000e+01,
        3.50000000e+01, 4.15115235e+01, 7.90185680e-02, 2.30000000e+01]])

In [6]:
# 答案 類別 標籤
y[:3]

array([0, 0, 0], dtype=int64)

In [7]:
# 特徵縮放（Feature Scaling） 常態化（Normalization） 
from sklearn.preprocessing import MinMaxScaler
mmx = MinMaxScaler() # Class 建立起來
X_mmx = mmx.fit_transform(X)

In [8]:
# 檢視縮放後的數據
pd.DataFrame(X_mmx[:3], columns = data.columns[1:-1])

Pregnancies  PlasmaGlucose  DiastolicBloodPressure  TricepsThickness  \
0     0.000000       0.858108                0.602151          0.313953   
1     0.571429       0.324324                0.741935          0.465116   
2     0.500000       0.479730                0.247312          0.523256   

   SerumInsulin       BMI  DiabetesPedigree       Age  
0      0.011465  0.668952          0.510511  0.000000  
1      0.028025  0.080352          0.036123  0.035714  
2      0.026752  0.616137          0.000438  0.035714

In [9]:
# 分割全部數據成為 訓練與驗證資料區 # sklearn.model_selection.train_test_split 
# https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_mmx, y, test_size=0.2, random_state=0)

In [10]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((12000, 8), (3000, 8), (12000,), (3000,))

In [11]:
# 載入模型
# # https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html#sklearn.neighbors.KNeighborsClassifier

In [12]:
## https://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPClassifier.html#sklearn.neural_network.MLPClassifier
# 換成 MLPClassifier
from sklearn.linear_model import LogisticRegression # 用 [LogisticRegression] algorithm 演算法
model = LogisticRegression(max_iter = 100)          # 建立模型 = 使用初始化參數
model.fit(X_train, y_train)                         # 餵入 資料+答案 訓練模型 train model 去 找出來模型最佳參數

LogisticRegression()

In [19]:
model.coef_ # model = weight = 係數 = 參數 # 模型最佳參數

array([[3.77520202, 1.35453766, 1.06838521, 1.90800613, 2.86879897,
        1.91588423, 2.13569302, 3.16770468]])

In [14]:
print(dir(model))

['C', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_check_n_features', '_estimator_type', '_get_param_names', '_get_tags', '_more_tags', '_predict_proba_lr', '_repr_html_', '_repr_html_inner', '_repr_mimebundle_', '_validate_data', 'class_weight', 'classes_', 'coef_', 'decision_function', 'densify', 'dual', 'fit', 'fit_intercept', 'get_params', 'intercept_', 'intercept_scaling', 'l1_ratio', 'max_iter', 'multi_class', 'n_features_in_', 'n_iter_', 'n_jobs', 'penalty', 'predict', 'predict_log_proba', 'predict_proba', 'random_state', 'score', 'set_params', 'solver', 'sparsify', 'tol', 'verbose', 'warm_start']


In [27]:
import numpy as np
np.sum(model.predict_proba(X_test), axis=1)[:5].reshape(-1, 1)

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [21]:
model.predict_proba(X_test)[:5]

array([[0.81117366, 0.18882634],
       [0.96129388, 0.03870612],
       [0.80545516, 0.19454484],
       [0.24469989, 0.75530011],
       [0.34342561, 0.65657439]])

In [23]:
# 分類預測 
model.predict(X_test)[:5].reshape(-1,1)

array([[0],
       [0],
       [0],
       [1],
       [1]], dtype=int64)

In [15]:
model.predict(X_test), y_test # score model

(array([0, 0, 0, ..., 1, 0, 1], dtype=int64),
 array([0, 0, 1, ..., 1, 1, 1], dtype=int64))

In [16]:
# 用你的方式 LOOP NUMPY 驗證出 預測 model.predict(X_test) 百分之百 等於 y_test
model.predict(X_test) == y_test

array([ True,  True, False, ...,  True, False,  True])

In [17]:
# 用你的方式 LOOP NUMPY 驗證出 預測 model.predict(X_test) 百分之百 等於 y_test
(model.predict(X_test) == y_test).sum() / len(y_test)

0.791

In [18]:
model.score(X_test, y_test) # evaluate

0.791

In [ ]:
# 用 [LogisticRegression] algorithm 演算法 去 建立 分類模型 再 預測 糖尿病患的狀況

In [ ]:
# Classification model
 # LogisticRegression algorithm 演算法
 # neural_network.MLPClassifier

In [ ]:
# Regression model
 # LinearRegression algorithm