In [2]:
import sys
sys.executable

'c:\\python37\\python.exe'

In [4]:
from sklearn import datasets
iris = datasets.load_iris()
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [6]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [11]:
# 花的數據
'''
        - sepal length in cm 花萼 長度
        - sepal width in cm  花萼 寬度
        - petal length in cm 花瓣 長度
        - petal width in cm  花瓣 寬度
'''    
#
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [7]:
# 花的種類
'''
                - Iris-Setosa      0
                - Iris-Versicolour 1
                - Iris-Virginica   2
'''
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [47]:
# 認識 特徵 features (花萼長度 花萼寬度 花瓣長度 花瓣寬度)
# 認識 標籤 labels   (Iris-Setosa-0, Iris-Versicolour-1, Iris-Virginica-2)
# 資料集 csv
'''
slength swidth plength pwidth class

'''
import pandas as pd
X = iris.data
y = iris.target
df = pd.DataFrame(X, columns=['slength','swidth','plength','pwidth'])
df['class'] = y
df[-3:]
# 輸出到 csv 不要 index 
df.to_csv('iris.csv', index = False)


In [32]:
# 一階張量 與 二階張量 差異
y[:3], y[:3].reshape(-1, 1)

(array([0, 0, 0]),
 array([[0],
        [0],
        [0]]))

In [30]:
# numpy 失敗
import numpy as np
import pandas as pd
X = iris.data
y = iris.target
np.hstack( (X, y) ) 

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [29]:
# numpy h: 水平合併
import numpy as np
import pandas as pd
X = iris.data
y = iris.target
pd.DataFrame( np.hstack( (X, y.reshape(-1, 1)) ) , 
              columns=['slength','swidth','plength','pwidth','class'])

slength  swidth  plength  pwidth  class
0        5.1     3.5      1.4     0.2    0.0
1        4.9     3.0      1.4     0.2    0.0
2        4.7     3.2      1.3     0.2    0.0
3        4.6     3.1      1.5     0.2    0.0
4        5.0     3.6      1.4     0.2    0.0
..       ...     ...      ...     ...    ...
145      6.7     3.0      5.2     2.3    2.0
146      6.3     2.5      5.0     1.9    2.0
147      6.5     3.0      5.2     2.0    2.0
148      6.2     3.4      5.4     2.3    2.0
149      5.9     3.0      5.1     1.8    2.0

[150 rows x 5 columns]

In [40]:
import numpy as np
np.stack?

In [43]:
X[:, 0].shape

(150,)

In [46]:
# numpy 
import numpy as np
import pandas as pd
X = iris.data
y = iris.target
np.stack( ( X[:, :1], y.reshape(-1,1) ) , axis = 1)

array([[[5.1],
        [0. ]],

       [[4.9],
        [0. ]],

       [[4.7],
        [0. ]],

       [[4.6],
        [0. ]],

       [[5. ],
        [0. ]],

       [[5.4],
        [0. ]],

       [[4.6],
        [0. ]],

       [[5. ],
        [0. ]],

       [[4.4],
        [0. ]],

       [[4.9],
        [0. ]],

       [[5.4],
        [0. ]],

       [[4.8],
        [0. ]],

       [[4.8],
        [0. ]],

       [[4.3],
        [0. ]],

       [[5.8],
        [0. ]],

       [[5.7],
        [0. ]],

       [[5.4],
        [0. ]],

       [[5.1],
        [0. ]],

       [[5.7],
        [0. ]],

       [[5.1],
        [0. ]],

       [[5.4],
        [0. ]],

       [[5.1],
        [0. ]],

       [[4.6],
        [0. ]],

       [[5.1],
        [0. ]],

       [[4.8],
        [0. ]],

       [[5. ],
        [0. ]],

       [[5. ],
        [0. ]],

       [[5.2],
        [0. ]],

       [[5.2],
        [0. ]],

       [[4.7],
        [0. ]],

       [[4.8],
        [0. ]],

       [