In [3]:
# 張量 = tensor 
# 0 rank tensor : scalar value 純量 零階張量
import numpy as np
data = np.array(0)
data.shape

()

In [5]:
# 1 rank tensor : vector 向量 一階張量
import numpy as np
data = np.array([0, 1, 2])
data.shape

(3,)

In [7]:
# 2 rank tensor : matrix 矩陣 二階張量
import numpy as np
data = np.array([
                 [0, 1, 2], 
                 [3, 4, 5]
               ])
data.shape

(2, 3)

In [10]:
# 3 rank+ tensor : array 陣列 多階張量
import numpy as np
data = np.array([
                 [
                  [0, 1, 2], 
                  [3, 4, 5]
                 ] ,
                 [
                  [1, 1, 1], 
                  [2, 2, 2]
                 ]
                ])
data.shape

(2, 2, 3)

In [17]:
# 張量的運算
import numpy as np
a = np.array([3, 1])
b = np.array([2, 3])
a.shape, b.shape
a, b
a + b

array([5, 4])

In [19]:
# 容易搞混
a = np.array([3, 1])
a.shape, a

((2,), array([3, 1]))

In [20]:
# 容易搞混
a = np.array([[3], 
              [1]])
a.shape, a

((2, 1),
 array([[3],
        [1]]))

In [21]:
# 互換 1-rank <--> 2-rank
a = np.array([3, 1])
a

array([3, 1])

In [27]:
# 互換 1-rank <--> 2-rank
a.reshape(-1,1), a.reshape(-1,1).shape

(array([[3],
        [1]]),
 (2, 1))

In [28]:
# 互換 1-rank <--> 2-rank
a.reshape(1,-1), a.reshape(1,-1).shape

(array([[3, 1]]), (1, 2))

In [31]:
# 互換 2-rank <--> 1-rank
b = np.array([[3, 1]])
b.shape

(1, 2)

In [33]:
# 互換 2-rank <--> 1-rank
b = np.array([[3, 1]])
b.flatten(), b.flatten().shape

(array([3, 1]), (2,))

In [34]:
# 互換 2-rank <--> 1-rank
b = np.array([[3, 1]])
b.ravel(), b.ravel().shape

(array([3, 1]), (2,))

In [ ]:
###################### 2-rank ---> 1-rank

In [36]:
# 互換 2-rank <--> 1-rank
c = np.array([[3], [1]])
c, c.shape

(array([[3],
        [1]]),
 (2, 1))

In [38]:
# 互換 2-rank <--> 1-rank
c = np.array([[3], [1]])
c.reshape(-1,), c.reshape(-1,).shape

(array([3, 1]), (2,))

In [39]:
# 互換 2-rank <--> 1-rank
c = np.array([[3], [1]])
c.ravel(), c.ravel().shape

(array([3, 1]), (2,))

In [41]:
# 互換 2-rank <--> 1-rank
c = np.array([[3], [1]])
c.flatten(), c.flatten().shape

(array([3, 1]), (2,))

In [49]:
# Exam
from numpy import random
data = random.randint(1, 6, (10,))
data.shape, data
# (10, 1)
data.reshape(-1, 1).shape

(10, 1)

In [50]:
# 相減
import numpy as np
a = np.array([3, 1])
b = np.array([2, 3])
a - b

array([ 1, -2])

In [67]:
# 二階張量 運算
import numpy as np
A = np.array([[1,2,3],
              [4,5,6]])
# A = 2 * 3
B = np.array([[9,8],
              [7,6],
              [5,4]])
# B = 3 * 2

np.dot(A, B), A.dot(B) , A@B, B.dot(A)

(array([[ 38,  32],
        [101,  86]]),
 array([[ 38,  32],
        [101,  86]]),
 array([[ 38,  32],
        [101,  86]]),
 array([[41, 58, 75],
        [31, 44, 57],
        [21, 30, 39]]))

In [68]:
# np.array * np.array

# 二階張量 運算
import numpy as np
A = np.array([[1, 1],
              [2, 2]])
# A = 2 * 2
B = np.array([[3, 3],
              [4, 4]])
# B = 2 * 2

A*B

array([[3, 3],
       [8, 8]])

In [66]:
# 二階張量 運算
import numpy as np
A = np.matrix([[1,2,3],
              [4,5,6]])
# A = 2 * 3
B = np.matrix([[9,8],
               [7,6],
               [5,4]])
np.dot(A, B), A*B, A@B, A.dot(B) # 當變數是matrix時候，可以使用 X*Y

(matrix([[ 38,  32],
         [101,  86]]),
 matrix([[ 38,  32],
         [101,  86]]),
 matrix([[ 38,  32],
         [101,  86]]),
 matrix([[ 38,  32],
         [101,  86]]))