In [1]:
# 匯入資料
import pandas as pd
iris = pd.read_csv('iris.csv')
iris[:3]

slength  swidth  plength  pwidth  class
0      5.1     3.5      1.4     0.2      0
1      4.9     3.0      1.4     0.2      0
2      4.7     3.2      1.3     0.2      0

In [5]:
import random
print(dir(random))

['BPF', 'LOG4', 'NV_MAGICCONST', 'RECIP_BPF', 'Random', 'SG_MAGICCONST', 'SystemRandom', 'TWOPI', '_Sequence', '_Set', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '_accumulate', '_acos', '_bisect', '_ceil', '_cos', '_e', '_exp', '_inst', '_log', '_os', '_pi', '_random', '_repeat', '_sha512', '_sin', '_sqrt', '_test', '_test_generator', '_urandom', '_warn', 'betavariate', 'choice', 'choices', 'expovariate', 'gammavariate', 'gauss', 'getrandbits', 'getstate', 'lognormvariate', 'normalvariate', 'paretovariate', 'randint', 'random', 'randrange', 'sample', 'seed', 'setstate', 'shuffle', 'triangular', 'uniform', 'vonmisesvariate', 'weibullvariate']


In [6]:
from numpy import random
print(dir(random))

['BitGenerator', 'Generator', 'MT19937', 'PCG64', 'Philox', 'RandomState', 'SFC64', 'SeedSequence', '__RandomState_ctor', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_bounded_integers', '_common', '_generator', '_mt19937', '_pcg64', '_philox', '_pickle', '_sfc64', 'beta', 'binomial', 'bit_generator', 'bytes', 'chisquare', 'choice', 'default_rng', 'dirichlet', 'exponential', 'f', 'gamma', 'geometric', 'get_state', 'gumbel', 'hypergeometric', 'laplace', 'logistic', 'lognormal', 'logseries', 'mtrand', 'multinomial', 'multivariate_normal', 'negative_binomial', 'noncentral_chisquare', 'noncentral_f', 'normal', 'pareto', 'permutation', 'poisson', 'power', 'rand', 'randint', 'randn', 'random', 'random_integers', 'random_sample', 'ranf', 'rayleigh', 'sample', 'seed', 'set_state', 'shuffle', 'standard_cauchy', 'standard_exponential', 'standard_gamma', 'standard_normal', 'standard_t', 'test', 'triangular', 'uni

In [30]:
# Modify a sequence in-place by shuffling its contents. 
# random.shuffle
X = np.array(list(range(12)))
y = np.array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2])
X , y

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]))

In [16]:
# 亂數挑選 80% 當訓練
# 剩下的 20% 當驗證

In [46]:
# 方法一
import numpy as np
idx = np.arange(0, 12)
print('Index before shuffle 打亂', idx)
random.shuffle(idx)
print('Index After shuffle 打亂', idx)
print('\n')
train_num = int(np.round(len(idx) * 0.8))
train_idx, test_idx = idx[:train_num], idx[train_num:]
print('train_idx 第幾個', train_idx)
print('test_idx 第幾個', test_idx)
print('\n')
train_X, train_y = X[train_idx], y[train_idx]
print('Train X & y 數值', train_X, train_y)

test_X, test_y = X[test_idx], y[test_idx]
print('Test X & y 數值', test_X ,test_y)

Index before shuffle 打亂 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Index After shuffle 打亂 [ 8 10  3  9  0  5  6  2  1 11  7  4]


train_idx 第幾個 [ 8 10  3  9  0  5  6  2  1 11]
test_idx 第幾個 [7 4]


Train X & y 數值 [ 8 10  3  9  0  5  6  2  1 11] [2 2 0 2 0 1 1 0 0 2]
Test X & y 數值 [7 4] [1 1]


In [ ]:
# (array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
#  array([ 0,  0,  0,  0,  1,  1,  1,  1,  2,  2,  2, 2]))

In [47]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
X_train, X_test, y_train, y_test

(array([10,  2,  8,  1,  7,  9,  3,  0,  5]),
 array([ 6, 11,  4]),
 array([2, 0, 2, 0, 1, 2, 0, 0, 1]),
 array([1, 2, 1]))

In [ ]:
# 請你使用 sklearn.model_selection.train_test_split
# 實作上面的分類 注意 random_state = 0