In [1]:
# 多分類 預測一個水果 是 香蕉 蘋果 芭樂 柳丁(只能 四種選一種) Multiclass --> 鳶尾花 分類就是 這個案例
# 多標籤 預測一篇文章 是 散文 時事 科技 文學(允許 多種選多種) MultiLabel
 
# https://scikit-learn.org/stable/modules/multiclass.html

In [26]:
# 匯入資料
import pandas as pd
iris = pd.read_csv('iris.csv')
iris[:3]

slength  swidth  plength  pwidth  class
0      5.1     3.5      1.4     0.2      0
1      4.9     3.0      1.4     0.2      0
2      4.7     3.2      1.3     0.2      0

In [27]:
# 補充 pandas --> numpy 
# DataFrame.values --> numpy 
iris.values[:3]

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ]])

In [28]:
#X 前面四個欄位的數值
#y 最後一個欄位的數值
X, y = iris.values[:, :4], iris.values[:, -1]

In [29]:
# 特徵
X[:3]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2]])

In [30]:
# 答案 類別 標籤
y[:3]

array([0., 0., 0.])

In [31]:
# 分割全部數據成為 訓練與驗證資料區 # sklearn.model_selection.train_test_split 
# https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [32]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((120, 4), (30, 4), (120,), (30,))

In [33]:
# train , test
150 * 0.8 , 150 * 0.2

(120.0, 30.0)

In [ ]:
# 載入模型
# # https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html#sklearn.neighbors.KNeighborsClassifier

In [34]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=1)
model.fit(X_train, y_train) # 餵入訓練資料

KNeighborsClassifier(n_neighbors=1)

In [35]:
model.predict(X_test), y_test # score model

(array([2., 1., 0., 2., 0., 2., 0., 1., 1., 1., 2., 1., 1., 1., 1., 0., 1.,
        1., 0., 0., 2., 1., 0., 0., 2., 0., 0., 1., 1., 0.]),
 array([2., 1., 0., 2., 0., 2., 0., 1., 1., 1., 2., 1., 1., 1., 1., 0., 1.,
        1., 0., 0., 2., 1., 0., 0., 2., 0., 0., 1., 1., 0.]))

In [38]:
# 用你的方式 LOOP NUMPY 驗證出 預測 model.predict(X_test) 百分之百 等於 y_test
(model.predict(X_test) == y_test).sum() / len(y_test)

1.0

In [23]:
model.score(X_test, y_test) # evaluate

1.0